### ISSUE TITLE
"Unable to generate network graph!" error when loading nod12b.map

### ISSUE THREAD

**Issue by MikillRosen** [whensonZWS/Trigger-Analyzer#7]
(TS map) [nod12b.zip](https://github.com/whensonZWS/Trigger-Analyzer/files/6295998/nod12b.zip)

**Comment by whensonZWS** [comment]
Programming error.
The logic of preventing the bug exists but did not work, due to me mistakenly believe that the FOR...IN... loop logic for arrays in javascript behaves the same way as it did in python. In reality the javascript iterate over index, and python iterate over array items and the bug prevention logic fails miserably.
Fix in commit `c31656b`
